# Generated by Django 3.2 on 2021-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.IntegerField()),
                ('map_name', models.CharField(max_length=50)),
                ('map_url', models.TextField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
