# Generated by Django 2.2.5 on 2021-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210511_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='map_id',
        ),
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
