# Generated by Django 2.2.5 on 2021-05-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210513_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
    ]
